# -*- coding: utf-8 -*-
import json

dados = {
    "71": {
        "correta": "E",
        "explicacao": "**Por que a alternativa E está correta:** No ciclo de Born-Haber para o NaCl, cada etapa corresponde a uma transformação distinta. A sublimação do sódio metálico (Na(s) -> Na(g)) é a etapa que transforma o metal sólido em gás, identificada como ∆H1. A primeira energia de ionização do sódio (Na(g) -> Na+(g) + e-) corresponde a ∆H3, pois remove um eletron do átomo gasoso. A afinidade eletronica do cloro (Cl(g) + e- -> Cl-(g)) corresponde a ∆H4, etapa em que o átomo de cloro recebe um eletron. Assim, na ordem pedida (sublimação, ionização e afinidade eletronica), os valores são ∆H1, ∆H3 e ∆H4.\n\nAs demais alternativas trocam a ordem ou associam etapas erradas a cada processo, confundindo, por exemplo, a sublimação com a dissociação do Cl2 ou a ionização com a afinidade eletronica.\n\n**Conceito-chave:** O ciclo de Born-Haber aplica a Lei de Hess para calcular a energia reticular de um cristal iônico de forma indireta, somando as variações de entalpia de etapas conhecidas: sublimação do metal, dissociação da molécula diatomica, energia de ionização do metal, afinidade eletronica do não metal e formação do retículo cristalino. Reconhecer corretamente o que ocorre em cada etapa fisica e quimica é essencial para associá-la ao ∆H correspondente."
    },
    "72": {
        "correta": "E",
        "explicacao": "**Por que a alternativa E está correta:** Comparando soluções de mesma concentração (0,1 mol/L), a maior concentração total de íons depende da quantidade de íons liberados por fórmula e do grau de dissociação. O sulfato de sódio (Na2SO4) é um sal solúvel que se dissocia totalmente liberando tres íons por fórmula (2 Na+ e 1 SO4^2-), produzindo a maior concentração total de íons entre as opções, enquanto HCl e NaOH liberam apenas dois íons e o ácido acético é fraco (pouco ionizado). Já a maior concentração de H+(aq) ocorre no ácido clorídrico, pois é um ácido forte que se ioniza completamente, ao contrario do ácido acético, que é fraco. Logo, a resposta é sulfato de sódio e ácido clorídrico.\n\nAs outras alternativas erram ao indicar o ácido acético (eletrólito fraco, baixa concentração de íons e de H+) ou o NaOH como fonte de maior concentração de H+, quando na verdade o hidróxido de sódio é uma base.\n\n**Conceito-chave:** Em soluções de igual concentração analítica, eletrólitos fortes que liberam mais íons por fórmula geram maior concentração total de íons; o Na2SO4 (3 íons) supera os monoácidos e monobases (2 íons). A acidez efetiva (concentração de H+) depende da força do ácido: ácidos fortes como o HCl se ionizam totalmente, ao passo que ácidos fracos como o acético se ionizam parcialmente."
    },
    "73": {
        "correta": "B",
        "explicacao": "**Por que a alternativa B está correta:** Reações de oxirredução envolvem transferencia de eletrons, ou seja, variação do número de oxidação (Nox) de elementos. No fenomeno 1, o cobre metálico (Nox 0) cede eletrons para os íons prata (Ag+ -> Ag0), oxidando-se a Cu2+ enquanto a prata se reduz; há oxirredução. No fenomeno 2, hidrogenio e oxigenio gasosos (ambos com Nox 0) reagem formando água, em que o H passa a +1 e o O a -2; também é oxirredução. Portanto, ocorrem reações de oxirredução somente nos fenomenos 1 e 2.\n\nNos fenomenos 3 (precipitação de CaCO3 a partir de CO2 e Ca(OH)2) e 4 (reação do vinagre, ácido, com o hidróxido de magnésio) não há variação de Nox: são, respectivamente, uma reação de dupla troca/precipitação e uma neutralização ácido-base, sem transferencia de eletrons.\n\n**Conceito-chave:** Para identificar uma reação de oxirredução, verifica-se se algum elemento muda seu número de oxidação durante a transformação. Reações entre substancias simples e formação de metais a partir de seus íons normalmente são redox, enquanto precipitações por dupla troca e neutralizações ácido-base ocorrem sem alteração de Nox."
    },
    "74": {
        "correta": "C",
        "explicacao": "**Por que a alternativa C está correta:** A vitamina K1 possui uma longa cadeia carbonica e um anel aromático com grupos apolares, o que a torna lipossolúvel (solúvel em gorduras), caracteristica das vitaminas A, D, E e K. Sua estrutura apresenta duplas ligações (no anel naftoquinona e na cadeia lateral), de modo que a cadeia carbonica é insaturada. Há na molécula átomo de carbono terciário (carbono ligado a outros tres carbonos, presente nas ramificações da cadeia). Por possuir dupla ligação com substituintes diferentes em cada carbono, a vitamina apresenta isomeria geométrica (cis-trans). Assim, as lacunas são preenchidas por lipossolúvel, insaturada, terciário e geométricos.\n\nAlternativas que indicam hidrossolúvel contrariam a natureza apolar da molécula; as que dizem saturada ignoram as duplas ligações; e as que apontam carbono quaternário ou isomeria óptica não correspondem à estrutura da vitamina K1, que não possui carbono quiral assimetrico característico nem carbono ligado a quatro outros carbonos no contexto pedido.\n\n**Conceito-chave:** A classificação de uma molécula organica envolve solubilidade (lipossolúvel para estruturas apolares, hidrossolúvel para polares), tipo de cadeia (saturada se só ligações simples, insaturada se há duplas/triplas), classificação dos carbonos (primário, secundário, terciário ou quaternário conforme o número de carbonos ligados) e tipo de isomeria (geométrica quando há dupla ligação com substituintes diferentes)."
    },
    "75": {
        "correta": "A",
        "explicacao": "**Por que a alternativa A está correta:** A etanolamina (NH2CH2CH2OH) possui um grupo álcool (-CH2OH) na extremidade da cadeia, enquanto a glicina é um aminoácido que apresenta um grupo carboxila (-COOH). A conversão de um grupo álcool primário em ácido carboxílico envolve aumento do número de oxidação do carbono (perda de hidrogenios e ganho de oxigenio), o que caracteriza uma reação de oxidação. Por isso, a transformação da etanolamina em glicina envolve uma reação de oxidação.\n\nAs demais alternativas não descrevem a mudança ocorrida: isomerização apenas rearranjaria a fórmula sem mudar grupos funcionais; esterificação formaria um éster; redução diminuiria o Nox do carbono (caminho inverso); e adição incorporaria átomos a uma insaturação, o que não ocorre aqui.\n\n**Conceito-chave:** A oxidação de álcoois primários gera, sucessivamente, aldeídos e ácidos carboxílicos, com aumento do número de oxidação do carbono da função. Comparar os grupos funcionais do reagente e do produto permite identificar se houve oxidação (álcool -> ácido) ou redução (sentido inverso)."
    },
    "76": {
        "correta": "D",
        "explicacao": "**Por que a alternativa D está correta:** O gráfico de velocidade por tempo é um trapézio (triangular nas fases de aceleração e frenagem), de modo que a distancia total percorrida entre os dois semáforos é a área sob o gráfico. Tanto na aceleração (tempo T1) quanto na frenagem (tempo T2) o veículo parte ou chega ao repouso, formando triangulos cuja área total é (Vmáx/2)(T1 + T2). A velocidade escalar média é a distancia total dividida pelo tempo total (T1 + T2), o que resulta em Vmáx/2. A alternativa D corresponde a essa expressão correta da velocidade média obtida pela razão entre a área (deslocamento) e o intervalo total de tempo.\n\nAs demais alternativas decorrem de cálculos incorretos da área sob a curva ou da combinação errada das acelerações e dos tempos, não refletindo a definição de velocidade média como deslocamento total dividido pelo tempo total.\n\n**Conceito-chave:** Em um gráfico de velocidade em função do tempo, a área sob a curva representa o deslocamento. A velocidade escalar média é o deslocamento total dividido pelo intervalo de tempo total; para movimentos que partem e terminam no repouso com fases triangulares, ela equivale à metade da velocidade máxima atingida."
    },
    "77": {
        "correta": "C",
        "explicacao": "**Por que a alternativa C está correta:** A esfera descreve um movimento circular em plano horizontal, configurando um pendulo conico. O fio faz um angulo com a vertical, e a tração (T) no fio tem duas componentes: a vertical (T·cos θ) equilibra o peso, e a horizontal (T·sen θ) fornece a resultante centripeta. Com fio de 65 cm e raio de 60 cm, a componente vertical do fio mede 25 cm (triangulo 25-60-65), logo cos θ = 25/65 e sen θ = 60/65. Pela componente vertical: T·cos θ = m·g, ou seja, T·(25/65) = 0,5·10 = 5 N. Isolando, T = 5·(65/25) = 13 N. Portanto, a tração no fio vale 13 N.\n\nAs outras alternativas resultam de erros na decomposição da tração, no uso da geometria do triangulo 25-60-65 ou na confusão entre as componentes vertical e horizontal da força.\n\n**Conceito-chave:** No pendulo conico, a tração do fio se decompoe em uma componente vertical, que equilibra o peso (T·cos θ = m·g), e uma componente horizontal, que atua como resultante centrípeta. A geometria do triangulo formado pelo fio, pelo raio e pela altura permite obter os senos e cossenos do angulo e, assim, calcular a tração."
    },
    "78": {
        "correta": "C",
        "explicacao": "**Por que a alternativa C está correta:** Como não há atrito nem resistencia do ar, vale a conservação da energia mecanica. No ponto 3, ponto mais alto da trajetória parabólica fora da pista, a velocidade da esfera é puramente horizontal, e essa componente horizontal se conserva durante todo o voo (movimento de projétil). Aplicando a conservação de energia entre o ponto de partida (em repouso) e o ponto 3, a diferença de altura entre eles corresponde à energia cinética associada à velocidade horizontal nesse ponto. Com os dados geométricos da pista (desníveis de 1,6 m e 1,8 m) e g = 10 m/s², o cálculo conduz a uma componente horizontal de módulo 2,0 m/s no ponto mais alto.\n\nAs demais alternativas resultam de uso incorreto das alturas envolvidas na conservação de energia ou da confusão entre a velocidade total no ponto 2 e a componente horizontal preservada no ponto 3.\n\n**Conceito-chave:** Na ausencia de atrito, a energia mecanica se conserva e a variação de energia potencial gravitacional se converte em energia cinetica. No lançamento de projétil, a componente horizontal da velocidade permanece constante; no ponto mais alto da trajetória, a velocidade é exclusivamente horizontal, igualando-se a essa componente conservada."
    },
    "79": {
        "correta": "E",
        "explicacao": "**Por que a alternativa E está correta:** Para o alarme disparar, a peça de platina deve aquecer de 20 oC até 80 oC, ou seja, uma variação de temperatura de 60 oC. A quantidade de calor necessária é Q = m·c·∆T = 200·0,03·60 = 360 cal. Convertendo para joules com 1 cal = 4 J, temos Q = 360·4 = 1440 J. Conhecendo a potencia fornecida pelo gráfico (2 W), o tempo é t = Q/P = 1440/2 = 720 s, que equivale a 12 min. Assim, o alarme disparará pela primeira vez em t = 12 min.\n\nAs outras alternativas decorrem de erros na conversão de calorias para joules, no cálculo da variação de temperatura (60 oC) ou na leitura da potencia no gráfico, levando a tempos incorretos.\n\n**Conceito-chave:** A quantidade de calor sensível necessária para variar a temperatura de um corpo é Q = m·c·∆T. Relacionando essa energia com a potencia recebida (P = Q/t), obtém-se o tempo de aquecimento. É essencial manter a coerencia de unidades, convertendo calorias em joules conforme o fator fornecido."
    },
    "80": {
        "correta": "D",
        "explicacao": "**Por que a alternativa D está correta:** Trata-se de um espelho esférico convexo, no qual a imagem formada é virtual, direita e menor que o objeto. A partir do raio de luz indicado e da geometria da figura, com as dimensões x e y dadas, aplica-se a relação entre triangulos semelhantes formados pelo objeto, pela imagem e pelos elementos do espelho (eixo principal, foco, centro de curvatura e vértice). A combinação correta dessas proporções, considerando as posições do objeto e da imagem A', conduz à expressão da distancia d em função de x e y apresentada na alternativa D.\n\nAs demais alternativas resultam de combinações incorretas entre x e y ou de relações geométricas mal aplicadas aos triangulos semelhantes da construção da imagem no espelho convexo.\n\n**Conceito-chave:** Em espelhos esféricos, a posição e o tamanho da imagem podem ser obtidos por construção geométrica com raios notáveis e por relações de semelhança de triangulos. No espelho convexo, a imagem é sempre virtual, direita e reduzida, e as proporções entre as dimensões lineares envolvidas permitem determinar distancias como a do objeto ao vértice."
    }
}

caminho = r"C:\Users\leo11\AndroidStudioProjects\aproveisimulado-data\scripts\_unesp2022expl_71_80.json"
with open(caminho, "w", encoding="utf-8") as f:
    json.dump(dados, f, ensure_ascii=False, indent=2)
print("OK", len(dados))
